FROM node:lts-alpine
WORKDIR /app
COPY ["./package.json", "package-lock.json", "./"]
RUN npm i
COPY . .

# ENV NODE_ENV = production
# ENV PORT = 5000
# ENV JWT_SECRET = 234672gh78r4cn2
# ENV MONGO_URI = mongodb+srv://marek1234:J83BiULs5cLA1p1l@cluster0.yg4mp.mongodb.net/odsi-fossa-db?retryWrites=true&w=majority

CMD ["npm", "start"]


